- public/index.html
> add teachable machine model

- script/seed.js
- server/db/models/exercise.js
- server/db/models/index.js
- server/db/models/set.js
- server/db/models/user.js
> feat: created User, Exercise and Set models, wrote associations

- client/components/Camera.js
- server/api/exercise.js
> fix: update to api route for logging exercise

- package-lock.json
- package.json
- public/index.html
> styling: installed Material-UI

- client/app.js
- client/components/Camera.js
- client/components/ExerciseLog.js
- client/components/StartWorkout.js
- client/theme.js
- server/api/exercise.js
> style: add mui theme and edit camera page

- client/components/Navbar.js
- client/theme.js
> style: fix button styling

- client/components/Camera.js
- client/components/ExerciseLog.js
- client/components/StartWorkout.js
- public/style.css
> style: remove overlap in startworkout page

- client/components/ExerciseLog.js
- client/components/StartWorkout.js
- script/seed.js
- server/api/exercise.js
- server/db/models/index.js
- server/db/models/set.js
> refactor: api routes and models

- client/components/ExerciseLog.js
- client/components/StartWorkout.js
- client/components/UserProfile.js
- client/components/UserProfile.spec.js
- client/components/index.js
- client/routes.js
> Refactor user home

- client/components/Navbar.js
- client/components/UserHome.js
- client/components/index.js
- client/routes.js
- package-lock.json
- package.json
- public/style.css
- script/seed.js
> update: add more users, sets, and associations

- client/components/WorkoutSummary.js
- client/theme.js
- package-lock.json
- package.json
- server/api/set.js
edit and delete funcationality in workout summary
> Workoutsummary

- client/routes.js
> fix: add workoutsummary import

- client/components/StartWorkout.js
> fix: remove stop camera ffect

- client/components/StartWorkout.js
- package-lock.json
- package.json
- script/seed.js
- server/api/exercise.js
- server/api/set.js
- server/db/models/set.js
> chore: add more seed data

- client/components/ExerciseLog.js
- client/components/StartWorkout.js
- client/components/WorkoutSummary.js
- server/api/exercise.js
> feat: log updates as user works out

- client/components/AddExercise.js
- client/components/WorkoutSummary.js
- script/seed.js
- server/api/exercise.js
- server/api/set.js
> Add a set manually in workout summary

- client/components/StartWorkout.js
> fix: fix bicep curl class name

- client/components/AddExercise.js
- client/components/Camera.js
- client/components/ExerciseLog.js
- client/components/Navbar.js
- client/components/StartWorkout.js
- client/components/UserProfile.js
- client/components/WorkoutSummary.js
- client/theme.js
- public/style.css
> Style/responsiveness/cleanup for StartWorkout and Camera components

- client/components/ExerciseLog.js
- client/components/UserHome.js
- client/components/WorkoutSummary.js
> workout summary / exercise log

- client/components/Camera.js
- client/components/StartWorkout.js
> feat: create new set if user takes a break of over 30s

- client/components/Camera.js
- client/components/ExerciseLog.js
- client/components/Navbar.js
- client/components/StartWorkout.js
- client/components/WorkoutSummary.js
> Responsive

- client/components/Navbar.js
- client/components/UserProfile.js
> fix: ma rginleft

- client/routes.js
> fix: all loggedIn user routes lead to UserHome

- client/components/UserHome.js
- public/style.css
> styling: calender & progress bar responsive

- client/components/Camera.js
- client/components/StartWorkout.js
> feat: error message if webcam access blocked

- script/seed.js
> chore: add new exercises

- client/components/UserProfile.js
- client/theme.js
- package-lock.json
- package.json
- public/style.css
> styling prototype with many comments

- client/components/UserHome.js
- client/components/WorkoutSummary.js
- server/auth/index.js
> fix: api route for updating user goal

- client/components/AddExercise.js
- client/components/UserHome.js
- client/components/UserProfile.js
- client/components/WorkoutSummary.js
- client/theme.js
- public/style.css
> update: responsive design for mobile

- client/components/AddExercise.js
- client/components/ProgressBar.js
- client/components/UserHome.js
- client/components/UserProfile.js
- client/components/WorkoutSummary.js
- client/theme.js
- public/style.css
> Progress bar

- client/components/ExerciseLog.js
> chore: add deadlifts to instructions

- client/components/AddExercise.js
- client/components/UserProfile.js
- client/components/WorkoutSummary.js
- public/style.css
> Styling update

- client/components/AddExercise.js
> fix: reps key

- client/components/AddExercise.js
> fix: remove glute bridge

- client/components/AuthForm.js
- client/components/ExerciseLog.js
- client/components/LandingPage.js
- client/components/Navbar.js
- client/components/ProgressBar.js
- client/components/StartWorkout.js
- client/components/UpdateGoalDialog.js
- client/components/UserHome.js
- client/components/UserProfile.js
- client/components/WorkoutSummary.js
- client/theme.js
- package.json
- server/auth/google.js
- server/auth/index.js
> chore: clean up console logs and unused var

- server/auth/index.js
> Fixed password update

- client/components/UserHome.js
> fix: different structure of data returned from DB

- client/components/UserHome.js
> fix: remove view of neighboring months

- client/app.js
- client/components/Camera.js
- client/components/StartWorkout.js
- client/components/WorkoutSummary.js
- client/context/WorkoutContext.js
- server/api/set.js
> fix: stop predict loop when camera stops

- client/components/StartWorkout.js
> chore: remove console logs

- .travis.yml
- client/components/UserProfile.spec.js
> travis: activate deployment

- client/components/UserHome.js
> style: grid align content

- client/components/ExerciseLog.js
> fix: keys for exercise log items
